### ISSUE TITLE
Video options from the right-click menu cannot be removed

### ISSUE THREAD

**Issue by LuisOseguera** [mariosemes/DrapTool#1]
I tried it for a long time, and after I stopped using it I decided to uninstall it. But happens that it wasn't completely uninstalled, as there's still the option for video files, even when I ran the document "unistall.bat" several times. Help! 😢

![image](https://user-images.githubusercontent.com/47401069/103315183-7b9d1880-49ea-11eb-84b6-0d0584bbd145.png)

**Comment by luisredondo** [comment]
Something could be wrong with "uninstall.bat" or perhaps something get corrupted while you were using this tool. 

Possible fix: According to the "install.bat" in the root directory of this repository, all the logic is handle it inside a folder called "DrapTool". So, [you could find that folder](https://superuser.com/questions/428088/find-a-directory-folder-with-cmd-without-knowing-full-path) and then delete it.

Let me know if this fix works for you.

**Comment by LuisOseguera** [comment]
> Something could be wrong with "uninstall.bat" or perhaps something get corrupted while you were using this tool.
> 
> Possible fix: According to the "install.bat" in the root directory of this repository, all the logic is handle it inside a folder called "DrapTool". So, [you could find that folder](https://superuser.com/questions/428088/find-a-directory-folder-with-cmd-without-knowing-full-path) and then delete it.
> 
> Let me know if this fix works for you.

Oh, thank you! Seems that your solution may work, but I fixed it by disabling the fields from the registry.

**Comment by mariosemes** [comment]
Apologies for the late answer.
Was sure that actually nobody is using it :D <3

I found the mistake and pushed an update + new release that should fix this issue.

Thanks for hanging in there!
